import * as T from 'three';
import {buildExterior} from './exterior.js';
import {OrbitControls} from './assets/OrbitControls.js';
const $=id=>document.getElementById(id), view=$('view');
try{await start()}catch(e){$('loading').style.display='block';$('loading').textContent='Model sa nepodarilo načítať. Skús obnoviť stránku v prehliadači s podporou WebGL.';console.error(e)}
async function start(){
const data=await fetch('./assets/model.json').then(r=>{if(!r.ok)throw Error('model');return r.json()});
const renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.setClearColor(0xdce6eb);view.append(renderer.domElement);renderer.outputColorSpace=T.SRGBColorSpace;
const scene=new T.Scene();scene.fog=new T.Fog(0xdce6eb,130,260);const camera=new T.PerspectiveCamera(48,innerWidth/innerHeight,.06,350);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.maxDistance=150;controls.minDistance=2;controls.maxPolarAngle=Math.PI*.49;controls.target.set(0,3,-3);
scene.add(new T.HemisphereLight(0xeaf6ff,0x9b9689,2.5));const sun=new T.DirectionalLight(0xfff3dc,3.2);sun.position.set(-28,70,22);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-55,right:55,top:55,bottom:-55,near:1,far:150});sun.shadow.bias=-.0002;scene.add(sun);
const mat=new T.MeshStandardMaterial({color:0xe6e4dd,roughness:.88}),sideMat=new T.MeshStandardMaterial({color:0xc5d1d4,roughness:.8}),slabMat=new T.MeshStandardMaterial({color:0xe4ddd0,roughness:.92}),glassMat=new T.MeshStandardMaterial({color:0x7aa7b7,transparent:true,opacity:.36,roughness:.2,metalness:.12}),frameMat=new T.MeshStandardMaterial({color:0x37494f});
function box(g,x,y,z,w,h,d,m){const mesh=new T.Mesh(new T.BoxGeometry(w,h,d),m);mesh.position.set(x,y,z);mesh.castShadow=true;mesh.receiveShadow=true;g.add(mesh);return mesh}
const ground=box(scene,0,-.5,0,210,.5,190,new T.MeshStandardMaterial({color:0xbccbc2,roughness:1}));const grid=new T.GridHelper(160,32,0xb1c1be,0xc5d1cc);grid.position.y=-.235;scene.add(grid);
const exterior=buildExterior();scene.add(exterior);
const groups=[],floorMeshes=[],roofMeshes=[];
// Simplified floor footprints, in metres, aligned to extracted drawing coordinates.
const footprints=[[[ -28.825,-23,28.825,-10.8],[-4.78,-10.8,5.02,-1.4],[-8.1,-1.4,10.3,15.85],[-13.3,15.85,-2.5,23]],[[ -28.825,-23,28.825,-10.8],[-4.78,-10.8,5.02,-1.4],[-8.1,-1.4,10.3,15.85],[-13.3,15.85,-2.5,23]],[[-23.675,-20.85,23.675,-12.1],[-4.78,-12.1,5.02,-1.4],[-8.1,-1.4,10.3,15.85]],[[-4.78,-9.32,4.86,-1.0]]];
const loader=new T.TextureLoader();const textures=[];
for(let f=0;f<4;f++){
 const group=new T.Group();group.position.y=data[f].base;scene.add(group);groups.push(group);floorMeshes[f]=[];roofMeshes[f]=[];
 const texture=loader.load(`assets/plan${f+1}.png`);texture.colorSpace=T.SRGBColorSpace;texture.anisotropy=renderer.capabilities.getMaxAnisotropy();textures.push(texture);
 for(const poly of data[f].walls){const shape=new T.Shape();poly.forEach((p,i)=>i?shape.lineTo(p[0],-p[1]):shape.moveTo(p[0],-p[1]));shape.closePath();const geo=new T.ExtrudeGeometry(shape,{depth:2.55,bevelEnabled:false});geo.rotateX(-Math.PI/2);const mesh=new T.Mesh(geo,[mat,sideMat]);mesh.castShadow=true;mesh.receiveShadow=true;group.add(mesh);}
 for(const w of data[f].windows){const [x,z,dx,dz]=w;const cx=x+dx/2,cz=z+dz/2;box(group,cx,2.38,cz,dx,.34,dz,mat);box(group,cx,1.15,cz,dx>.5?dx:.045,2.1,dz>.5?dz:.045,glassMat);if(dx>dz){for(const xx of [x+.025,x+dx-.025])box(group,xx,1.15,cz,.045,2.1,.065,frameMat)}else{for(const zz of [z+.025,z+dz-.025])box(group,cx,1.15,zz,.065,2.1,.045,frameMat)}}
 for(const [x,z,x1,z1] of footprints[f]){floorMeshes[f].push(box(group,(x+x1)/2,-.11,(z+z1)/2,x1-x,.22,z1-z,slabMat));const roof=box(group,(x+x1)/2,2.67,(z+z1)/2,x1-x,.22,z1-z,sideMat);roofMeshes[f].push(roof)}
 const geo=new T.PlaneGeometry(62,52);geo.rotateX(-Math.PI/2);const plan=new T.Mesh(geo,new T.MeshBasicMaterial({map:texture,transparent:true,opacity:.94,depthWrite:false}));plan.position.set(.175,.016,0);plan.visible=false;group.add(plan);group.userData.plan=plan;
}
// The pool location follows the 1.NP plan; depth and finish are illustrative.
box(groups[0],-13.15,.04,-16.1,9.6,.08,4.6,new T.MeshStandardMaterial({color:0x5da9ba,roughness:.22,transparent:true,opacity:.86}));
let selected='all', mode='orbit', yaw=0,pitch=0,keys={},drag=null;const clock=new T.Clock();
function status(){ $('status').textContent=`${selected==='all'?'Celá budova':`${selected+1}. NP`} · ${mode==='walk'?'prechádzka':'obhliadka'}`;$('orbit').classList.toggle('active',mode==='orbit');$('walk').classList.toggle('active',mode==='walk');document.body.classList.toggle('walking',mode==='walk') }
function visibility(){exterior.visible=selected==='all';ground.visible=selected!=='all';grid.visible=selected!=='all';for(let f=0;f<4;f++){groups[f].visible=selected===f;roofMeshes[f].forEach(r=>r.visible=selected==='all');groups[f].userData.plan.visible=$('plan').checked&&selected===f} $('maptitle').textContent=`${(selected==='all'?1:selected)+1}. NP`;$('mapimg').src=`assets/plan${(selected==='all'?1:selected)+1}.png`;status()}
function orbitHome(top=false){mode='orbit';controls.enabled=true;const y=selected==='all'?4:data[selected].base;camera.up.set(0,1,0);camera.position.set(top?0:61,top?95:40,top?-.01:63);controls.target.set(0,y,-1);controls.update();$('dot').style.display='none';$('hint').textContent='Ťahaním otáčaj model. Kolieskom približuj. Pravým tlačidlom posúvaj.';status()}
function walkAt(x=2.3,z=-4.1,outside=false){if(selected==='all'&&!outside){selected=1;$('floor').value='1';visibility()}mode='walk';controls.enabled=false;camera.position.set(x,(selected==='all'?0:data[selected].base)+1.65,z);yaw=0;pitch=0;camera.rotation.order='YXZ';camera.rotation.set(0,0,0);$('hint').textContent='W A S D alebo šípky: pohyb. Ťahaním sa rozhliadaj. Shift: rýchlejšie. Esc: obhliadka. Na mobile použi šípky.';status()}
$('floor').onchange=()=>{selected=$('floor').value==='all'?'all':Number($('floor').value);visibility();if(mode==='walk'&&selected!=='all')walkAt(selected===3?1:2.3,selected===3?-5:-4.1);else orbitHome()};$('orbit').onclick=()=>orbitHome();$('walk').onclick=()=>selected==='all'?walkAt(5,-31,true):walkAt();$('top').onclick=()=>orbitHome(true);$('reset').onclick=()=>orbitHome();$('plan').onchange=visibility;$('panelToggle').onclick=()=>$('panel').classList.toggle('open');
$('map').onclick=e=>{const r=$('map').getBoundingClientRect();walkAt((e.clientX-r.left)/r.width*62-30.825,(e.clientY-r.top)/r.height*52-26);$('panel').classList.remove('open')};
const canvas=renderer.domElement;canvas.addEventListener('pointerdown',e=>{if(mode==='walk'){drag={x:e.clientX,y:e.clientY,id:e.pointerId};canvas.setPointerCapture(e.pointerId)}});canvas.addEventListener('pointermove',e=>{if(drag&&mode==='walk'){yaw-=(e.clientX-drag.x)*.004;pitch=Math.max(-1.35,Math.min(1.35,pitch-(e.clientY-drag.y)*.004));drag.x=e.clientX;drag.y=e.clientY}});canvas.addEventListener('pointerup',()=>drag=null);canvas.addEventListener('pointercancel',()=>drag=null);
const mapped={ArrowUp:'w',ArrowDown:'s',ArrowLeft:'a',ArrowRight:'d'};window.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName))return;const k=mapped[e.key]||e.key.toLowerCase();keys[k]=true;if(mode==='walk'&&['w','a','s','d'].includes(k))e.preventDefault();if(e.key==='Escape')orbitHome()});window.addEventListener('keyup',e=>{keys[mapped[e.key]||e.key.toLowerCase()]=false});window.addEventListener('blur',()=>{keys={};drag=null});document.querySelectorAll('[data-move]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys[b.dataset.move]=true};b.onpointerup=b.onpointercancel=()=>keys[b.dataset.move]=false});
function inside(x,z,p){let c=false;for(let i=0,j=p.length-1;i<p.length;j=i++){const a=p[i],b=p[j];if((a[1]>z)!==(b[1]>z)&&x<(b[0]-a[0])*(z-a[1])/(b[1]-a[1])+a[0])c=!c}return c}
function canMove(x,z){if(selected==='all'||$('free').checked)return true;return !data[selected].walls.some(p=>[[0,0],[.18,0],[-.18,0],[0,.18],[0,-.18]].some(o=>inside(x+o[0],z+o[1],p)))}
function resize(){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)}window.addEventListener('resize',resize);visibility();orbitHome();$('loading').style.display='none';renderer.setAnimationLoop(()=>{const dt=Math.min(clock.getDelta(),.05);if(mode==='walk'){camera.rotation.set(pitch,yaw,0,'YXZ');if(selected==='all'){const x=camera.position.x,z=camera.position.z;const elevated=z>-2.5&&z<23.5&&((x>-32.5&&x<-13.5)||(x>15.5&&x<34.5));camera.position.y=(elevated?2.58:.05)+1.65}const f=(keys.w?1:0)-(keys.s?1:0),r=(keys.d?1:0)-(keys.a?1:0),norm=Math.hypot(f,r)||1,speed=(keys.shift?6:2.7)*dt/norm,dx=(-Math.sin(yaw)*f+Math.cos(yaw)*r)*speed,dz=(-Math.cos(yaw)*f-Math.sin(yaw)*r)*speed;const x=Math.max(-70,Math.min(70,camera.position.x+dx)),z=Math.max(-70,Math.min(70,camera.position.z+dz));if(canMove(x,camera.position.z))camera.position.x=x;if(canMove(camera.position.x,z))camera.position.z=z;const mx=(camera.position.x+30.825)/62,mz=(camera.position.z+26)/52;$('dot').style.display=mx>=0&&mx<=1&&mz>=0&&mz<=1?'block':'none';$('dot').style.left=mx*100+'%';$('dot').style.top=mz*100+'%'}else controls.update();renderer.render(scene,camera)});
}
